### ISSUE TITLE
很久没同步cdnjs了嘛

### ISSUE THREAD

**Issue by aufula** [bootcss/bootcdn#2]
还同步么？还维护么

**Comment by wangsai** [comment]
您好，谢谢您对 BootCDN的支持！

BootCDN 的官方仓库已经转到 https://github.com/bootcdn/cdnjs

BootCDN 每隔两天同步一次 cdnjs，如果遇到重要的开源项目（例如 jQuery／bootstrap等）更新，我们会第一时间同步cdnjs或直接更新 BootCDN 仓库。
